openapi: 3.1.0
components:
  schemas:
    AlertStatus:
      type: string
      enum: [ACTIVE, TRIGGERED, PAUSED]

    AlertChannel:
      type: string
      enum: [APP_WIDGET, EMAIL]

    AlertCreateRequest:
      type: object
      required: [productId, productName, productCurrentPrice]
      properties:
        productId: { type: string }
        userId: { type: string, description: "Populated from auth token; clients may omit." }
        productBrand: { type: string, description: "Brand snapshot captured when the alert is created." }
        productImage: { type: string, description: "Inline/base64 snapshot of the product image if available." }
        productImageUrl: { type: string, format: uri, description: "Canonical product image URL snapshot." }
        productUrl: { type: string, format: uri, description: "Canonical product page URL snapshot." }
        desiredPrice: { type: number, format: double, minimum: 0 }
        desiredPercent: { type: number, format: double, minimum: 0, maximum: 100 }
        alertIfSale: { type: boolean, default: false }
        channels:
          type: array
          items: { $ref: '#/components/schemas/AlertChannel' }
        productName: { type: string }
        productOriginalPrice: { type: number, format: double, minimum: 0 }
        productCurrentPrice: { type: number, format: double, minimum: 0 }

    AlertUpdateRequest:
      type: object
      properties:
        productId: { type: string }
        userId: { type: string, description: "Populated from auth token; clients may omit." }
        productBrand: { type: string }
        productImage: { type: string }
        productImageUrl: { type: string, format: uri }
        productUrl: { type: string, format: uri }
        desiredPrice: { type: number, format: double, minimum: 0 }
        desiredPercent: { type: number, format: double, minimum: 0, maximum: 100 }
        alertIfSale: { type: boolean }
        channels:
          type: array
          items: { $ref: '#/components/schemas/AlertChannel' }
        productName: { type: string }
        productOriginalPrice: { type: number, format: double, minimum: 0 }
        productCurrentPrice: { type: number, format: double, minimum: 0 }
        resetStatus: { type: boolean }

    AlertResponse:
      type: object
      properties:
        productId: { type: string }
        userId: { type: string }
        productName: { type: string }
        productBrand: { type: string }
        productImage: { type: string }
        productImageUrl: { type: string, format: uri }
        productUrl: { type: string, format: uri }
        productOriginalPrice: { type: number, format: double }
        productCurrentPrice: { type: number, format: double }
        desiredPrice: { type: number, format: double }
        desiredPercent: { type: number, format: double }
        alertIfSale: { type: boolean }
        channels:
          type: array
          items: { $ref: '#/components/schemas/AlertChannel' }
        status:
          $ref: '#/components/schemas/AlertStatus'
        lastTriggeredAt: { type: string, format: date-time }
        createdAt: { type: string, format: date-time }
        updatedAt: { type: string, format: date-time }
